services:
  postgres-db:
    image: postgres:17
    container_name: vistanhr-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vistanhr_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d vistanhr_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  spring-app:
    build: .
    container_name: vistanhr-app
    ports:
      - "8080:8080"
    environment:
      # ВАЖНО: вместо localhost пишем имя сервиса базы данных из этого же файла!
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/vistanhr_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  pgdata:

    #type in terminal of project "docker-compose up -d" for initialize the DB