server.port=8080

spring.datasource.url=jdbc:h2:file:./data/vistanhrdb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Email (для теста - не отправляет)
spring.mail.host=localhost
spring.mail.port=25
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

app.admin.email=admin@vistan.by

logging.level.org.example.vistanhr=INFO